---
name: s-1-9-0-hfx3-experiment-aaa-hackme-desktop
fields_under_root: false
queue:
  mem:
    events: 4096
    flush:
      min_events: 0
      timeout: 0s
logging:
  level: info
  selectors: :undef
  to_syslog: false
  to_eventlog: false
  json: false
  to_files: true
  files:
    path: "/var/log/auditbeat"
    name: auditbeat
    keepfiles: 7
    rotateeverybytes: 10485760
    permissions: '0600'
  metrics:
    enabled: true
    period: 30s
output:
  logstash:
    hosts:
      - 10.159.113.4:5044
auditbeat:
  modules:
    - module: auditd
      enabled: true
      audit_rule_files: "${path.config}/audit.rules.d/*.conf"

    - module: system
      datasets:
        - user
        - login
      user.detect_password_changes: true
      period: 3s
      state.period: 12h
