create table forummessage (message_id BIGINT NOT NULL AUTO_INCREMENT, message VARCHAR(255), viewsnumber BIGINT, creationdate DATETIME, user_id BIGINT, fk_parent_id BIGINT, primary key (message_id))
create table user_role (user_id BIGINT not null, role_id BIGINT not null, primary key (role_id, user_id))
create table usertable (id BIGINT NOT NULL AUTO_INCREMENT, username VARCHAR(255), password VARCHAR(255), firstName VARCHAR(255), lastName VARCHAR(255), icq INTEGER, aim VARCHAR(255), msn VARCHAR(255), yahoo VARCHAR(255), webSite VARCHAR(255), localisation VARCHAR(255), job VARCHAR(255), hobbies VARCHAR(255), signature VARCHAR(255), primary key (id))
create table forumcategory (cat_id BIGINT NOT NULL AUTO_INCREMENT, cattitle VARCHAR(255), catdescription VARCHAR(255), componentposition BIGINT, creationdate DATETIME, primary key (cat_id))
create table forumitem (forumitem_id BIGINT NOT NULL AUTO_INCREMENT, forumitemtitle VARCHAR(255), forumitemdescription VARCHAR(255), componentposition BIGINT, creationdate DATETIME, fk_parent_id BIGINT, primary key (forumitem_id))
create table role (id BIGINT NOT NULL AUTO_INCREMENT, rolename VARCHAR(255), primary key (id))
create table forumthread (forumthread_id BIGINT NOT NULL AUTO_INCREMENT, forumthreadtitle VARCHAR(255), componentposition BIGINT, creationdate DATETIME, fk_parent_id BIGINT, primary key (forumthread_id))
alter table forummessage add index (fk_parent_id), add constraint FK9FB79BC66F0645D6 foreign key (fk_parent_id) references forumthread (forumthread_id)
alter table user_role add index (role_id), add constraint FK143BF46A52119584 foreign key (role_id) references role (id)
alter table user_role add index (user_id), add constraint FK143BF46AF73AEE0F foreign key (user_id) references usertable (id)
alter table forumitem add index (fk_parent_id), add constraint FK7A458FB46F0645D6 foreign key (fk_parent_id) references forumcategory (cat_id)
alter table forumthread add index (fk_parent_id), add constraint FK11427E6B6F0645D6 foreign key (fk_parent_id) references forumitem (forumitem_id)