# The relay's own firewall (it conflicts with the other firewall modules, so it is the only one on the system).
# A script works out the internal and lab subnets on the VM and writes /etc/nftables.conf. nftables is enabled
# but not started: the rules apply from the next boot (the post-build reboot), so they can't cut off vagrant's
# SSH over the provisioning NIC while later modules are still being provisioned.
class llm_relay::firewall {
  require llm_relay::config
  Exec { path => ['/bin', '/usr/bin', '/usr/local/bin', '/sbin', '/usr/sbin'] }

  $secgen_parameters = secgen_functions::get_parameters($::base64_inputs_file)
  $listen_port       = $secgen_parameters['listen_port'][0]
  $allowed_networks  = $secgen_parameters['allowed_networks'].filter |$n| { $n != '' }
  $lab_inbound_ports = $secgen_parameters['lab_inbound_ports'].filter |$p| { $p != '' }
  $internal_network  = $::secgen_internal_network

  # the firewall needs the upstream as an IP (no DNS is allowed out)
  $upstream_url = regsubst($secgen_parameters['upstream_url'][0], '/+$', '')
  if $upstream_url =~ /^(https?):\/\/(\d+\.\d+\.\d+\.\d+)(:(\d+))?$/ {
    $upstream_host = $2
    if $4 {
      $upstream_port = $4
    } elsif $1 == 'https' {
      $upstream_port = '443'
    } else {
      $upstream_port = '80'
    }
  } else {
    fail("llm_relay: upstream_url must be http(s)://<IP>[:port] for the firewall rules, got '${upstream_url}'")
  }

  file { '/usr/local/sbin/secgen-llm-relay-firewall':
    ensure  => file,
    content => template('llm_relay/secgen-llm-relay-firewall.sh.erb'),
    mode    => '0700',
    owner   => 'root',
    group   => 'root',
  }
  exec { 'generate llm_relay firewall rules':
    command => '/usr/local/sbin/secgen-llm-relay-firewall',
    unless  => '/usr/local/sbin/secgen-llm-relay-firewall --check',
    require => [File['/usr/local/sbin/secgen-llm-relay-firewall'], Package['nftables']],
  }
  exec { 'enable nftables at boot':
    command => 'systemctl enable nftables',
    unless  => 'systemctl is-enabled nftables',
    require => Exec['generate llm_relay firewall rules'],
  }

  # the relay must never route between the lab and internal networks
  file { '/etc/sysctl.d/90-secgen-llm-relay.conf':
    ensure  => file,
    content => "# Generated by SecGen (llm_relay): no routing between the lab and internal networks\nnet.ipv4.ip_forward = 0\nnet.ipv6.conf.all.forwarding = 0\n",
    mode    => '0644',
  }
  exec { 'apply llm_relay sysctl':
    command     => 'sysctl -p /etc/sysctl.d/90-secgen-llm-relay.conf',
    refreshonly => true,
    subscribe   => File['/etc/sysctl.d/90-secgen-llm-relay.conf'],
  }
}
