ALERTER_DIRECTORY = File.expand_path(File.dirname(__FILE__))
CONFIG_DIRECTORY = ALERTER_DIRECTORY + 'config/'
LIB_DIRECTORY = ALERTER_DIRECTORY + 'lib/'
AA_CONFIG_SCHEMA = LIB_DIRECTORY + 'alertactioner_config_schema.xsd'
TEMPLATES_DIRECTORY = ALERTER_DIRECTORY + 'templates/'
COMMANDS_DIRECTORY = CONFIG_DIRECTORY + 'commands/'